### ISSUE TITLE
Ignore handshake errors

### ISSUE THREAD

**Issue by tijevlam** [follow-redirects/follow-redirects#99]
I’m struggling with thisnpm module for a project.
The thing is: it keeps giving me errors on the fact that some links have a certificate error:
 
```
{ Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
```
 
I know these should be fixed best at server level, but in my project im checking redirects from others (on servers I don’t control). Is there any way I could let the module ignore these errors and just show me whether a link is redirected and where to?

I found `insecure: false` and `requestCert:true` but those are only if you use createServer. I also found `process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;` but i dont want to reject them, i just want to ignore the error and follow the redirects (or let me know there arent any).
 
Hope to hear from you!

**Comment by RubenVerborgh** [comment]
If you don't want to reject, setting the env flag to 0 is what you want.
The default behavior is rejecting, which is what you are seeing now.

**Comment by tijevlam** [comment]
> If you don't want to reject, setting the env flag to 0 is what you want. The default behavior is rejecting, which is what you are seeing now.

He @RubenVerborgh , thanks for your reply.The problem with the env flag is that the redirect is not being followed and the `response.redirects` array is left empty.

**Comment by RubenVerborgh** [comment]
That's weird. Do you have an example?
